### PR TITLE
Update testing.md

### PR DESCRIPTION
**Pull request by cgwalters-testing**

### CODE REVIEW

**Comment by cgwalters-testing** [comment]
@cgwalters-bot r+

**Comment by cgwalters** [comment]
@cgwalters-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@rh-atomic-bot r+

**Comment by cgwalters** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
